version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types: 
          - "patch"
          - "minor"

